server {
    listen 80;
    server_name stanczak.ddns.net;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name stanczak.ddns.net;

    ssl_certificate /etc/letsencrypt/live/stanczak.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stanczak.ddns.net/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 20M;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /vektor/;
    }

    location /vektor/api/ {
        rewrite ^/vektor/api/(.*)$ /api/$1 break;

        proxy_pass http://backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /vektor/ {
        rewrite ^/vektor/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }
}